### PR TITLE
[Issue 4] Support multiple word elements for google docs lines

### PR DESCRIPTION
**Pull request by Raffinate**
Fix for https://github.com/Amaimersion/google-docs-utils/issues/4

### CODE REVIEW

**Comment by VolCh** [comment]
@Amaimersion is it going to be merged?

**Comment by srgykuz** [comment]
@Raffinate first of all, sorry for long waiting. And thank you very much for contributing!

The reason why I didn't merged your PR is that there should be a little bit different changes. Initially it was as you suggested (6c899cae2b34b85b46935375311b00dd7268d5be), but later I've changed it to a7e2f201dc20db8c132eb0d4cf5fea6a11809cd7. The reason is that with first change it will be very complicated to map word nodes with line that belongs to these word nodes. But with second change you will exactly know what word nodes every line contains, and you will know that word nodes have different formatting.

`getWordElements()` used by many other methods. So, other methods should have been changed also.

Unfortunately, such changes are breaking changes. If you will decide to upgrade from 2.1 version to 2.2, you may need to perform some little changes in your code. See changelog for more.

Anyway, thank you for pointing on this problem and your PR.

**Comment by srgykuz** [comment]
@VolCh available in v2.2.0.

**Comment by VolCh** [comment]
@Amaimersion thank you

**Pull request closed without merging**
